@MonApi_HostAddress = http://localhost:5270


GET {{MonApi_HostAddress}}/prenoms/
Accept: application/json

###
GET {{MonApi_HostAddress}}/prenoms/4
Accept: application/json

###
POST {{MonApi_HostAddress}}/prenoms
Content-Type: application/json

"Guillaume"


###
PUT {{MonApi_HostAddress}}/prenoms/4
Content-Type: application/json

"Margaux"
###
DELETE {{MonApi_HostAddress}}/prenoms/5

###